name: Deployment - DEV

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "eu-central-1"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_API_TOKEN: ${{ secrets.TERRAFORM_TOKEN }}
  TF_WORKING_DIRECTORY: "infra/terraform/dev"

jobs:
  infrastructure:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIRECTORY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color

  code:
    name: "Deploy Code"
    needs: infrastructure
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNTID }}:role/GithubTrigger
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Code
        run: |
          set -e
          make deploy ENV=dev
          # Add health check command here
          echo "Deployment version: $(git rev-parse --short HEAD)" >> $GITHUB_STEP_SUMMARY
